mongodb:
  host: localhost
# www service
www:
  home: http://localhost:8080
  port: 8080
# url service
url:
  base: http://localhost/%s
  length: 1
  unique: false
  humanity: false
  algorithm: 1 # 0 - random string; 1 - auto increment 